name: LobbyItems
version: 1.0
api: [3.0.0-ALPHA11]
main: R\LobbyItems
author: TR
commands:
    build:
        description: Lobby Buildmode
    lobby:
        description: Lobby
    fly:
        description: Fly Command
